### ISSUE TITLE
error on deployment - dev-appgateway-pfx PR/branch

### ISSUE THREAD

**Issue by ahmedsza** [cykreng/Enterprise-Scale-APIM#58]
Get this error when running deployment
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"NotFound\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceNotFound\\\",\\r\\n    \\\"message\\\": \\\"The Resource 'Microsoft.ApiManagement/service/apim-ahmsWL-dev-westeurope-001' under resource group 'rg-apim-ahmsWL-dev-westeurope-001' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\\\"\\r\\n  }\\r\\n}\"\r\n

![image](https://user-images.githubusercontent.com/37135205/148519857-2fc69cf0-f879-47bc-adf9-89b06ab5e163.png)

**Comment by briandenicola** [comment]
Closing the pull request and rebasing from main. I will sync my changes and reopen the pull
