### ISSUE TITLE
DNS Creation happening before API Management is ready

### ISSUE THREAD

**Issue by petemessina** [cykreng/Enterprise-Scale-APIM#61]
In the main bicep the shared/dnszone.bicep is sometimes being created before the API Management is ready. It looks like we need to add a dependsOn to the module.

**Comment by briandenicola** [comment]
I think the dnzson.bicep should be split into two - one to create the zones and one to create the DNS records in the zones. The zone creation should come first and should be completed before APIM is stood up.  The DNS records can only be done after APIM is created.

**Comment by aionic** [comment]
This is fixed in the main refactor
![image](https://user-images.githubusercontent.com/9543466/151883105-ac341fce-80f0-4d2e-977e-0734373f9f7d.png)
