### ISSUE TITLE
Storage account name can only be lowercase letters and numbers

### ISSUE THREAD

**Issue by cykreng** [cykreng/Enterprise-Scale-APIM#68]
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/37597107/151476512-76344cff-d57c-4614-9810-a5be0ed725c5.png">

**Comment by aionic** [comment]
The issue in this case is the "-" for the storage account

Changes in main.bicep
- Changed description
- Set character max length 

Change in module
- Changed description
- Set character max length 
- Added a replace to remove "-"
- Shorten variable name to allow more characters
